
---

- name: deploy cf
  shell: bosh -e spacex -d cf deploy /opt/spacex/workspaces/cf-deployment/cf-deployment.yml --vars-store /opt/spacex/workspaces/cf-vars.yml -o /opt/spacex/workspaces/cf-deployment/operations/openstack.yml -o /opt/spacex/workspaces/cf-deployment/operations/custom/use-haproxy.yml -v system_domain={{cf_system_domain}} -v haproxy_public_ip=`bosh int /opt/spacex/tf/terraform-vars.yml --path /cf_haproxy_public_ip` -n
  args:
    executable: /bin/bash

- name: generate cf login command
  shell: '{{item}}'
  args:
    executable: /bin/bash
  with_items:
    - /opt/spacex/scripts/generate-cl.sh `bosh int /opt/spacex/wise-stack-playbook/group_vars/all.yml --path /cf_system_domain`
    - cl

- name: enable cf feature flag
  shell: cf enable-feature-flag diego_docker
  args:
    executable: /bin/bash
